const animals = [
    // Water Creatures
    "Mollusk",
    "Crab / Lobster",
    "Squid / Octopus",
    "Mudskipper",
    "Jellyfish",
    "Deep Sea Fish",
    "Fresh Water Fish",
    "Whale / Dolphin",
    "Shell",
    "Eel",
    "Leech",
    "Coral / Anemone",
    "Shark",
    "Singray / Manta Ray",

    // Reptiles
    "Crocodile",
    "Gila",
    "Frog",
    "Newt",
    "Lizard",
    "Snake",
    "Turtle",

    // Bugs
    "Worm",
    "Ant",
    "Mosquito",
    "Moth",
    "Butterfly",
    "Fly",
    "Dragonfly",
    "Lotus",
    "Mantis",
    "Bee / Wasp",
    "Caterpillar",
    "Beetle",
    "Flea / Mite",
    "Spider",

    //Birds
    "Duck",
    "Heron",
    "Finch",
    "Crow",
    "Raven",
    "Hawk",
    "Falcon",
    "Rooster",
    "Chickadee",
    "Jay",
    "Parrot",
    "Robin",
    "Sparrow",
    "Seagull",
    "Dove",
    "Pigeon",
    "Owl",
    "Puffin",

    // Mammals
    "Sheep / Ram",
    "Cow / Bull",
    "Mouse / Rat",
    "Rabbit",
    "Pig / Boar",
    "Deer / Pronghorn / Buck",
    "Elephant",
    "Giraffe",
    "Bat",
    "Bear",
    "Wolf",
    "Fox",
    "Coyote",
    "Horse / Zebra",
    "Lion / Tiger",
    "Primate",
    "Hedgehog",
    "Opossum",
    "Raccoon",
    "Pink Fairy Armadillo",
    "Panda",
    "Otter",
    "Hyena"
]

export default animals;