const weapons = [
    "Club",
    "Dagger",
    "Greatclub",
    "Handaxe",
    "Javelin",
    "Light Hammer",
    "Mace",
    "Quarterstaff",
    "Sickle",
    "Spear",
    "Crossbow",
    "Dart",
    "Shortbow",
    "Sling",
    "Battleaxe",
    "Flail",
    "Glaive",
    "Greataxe",
    "Greatsword",
    "Halberd",
    "Lance",
    "Longsword",
    "Maul",
    "Morningstar",
    "Pike",
    "Rapier",
    "Scimitar",
    "Shortsword",
    "Trident",
    "War Pick",
    "Warhammer",
    "Whip",
    "Blowgun",
    "Longbow",
    "Net"
]

const equipment = [
    "Abacus",
    "Vial of Acid",
    "Flask of Alchemist's Fire",
    "Ammunition (arrows, blowgun needles, crossbow bolts, bullets, etc.)",
    "Vial of Antitoxin / Antidote",
    "Arcane Focus",
    "Backpack",
    "Bag of Ball Bearings",
    "Barrel",
    "Basket",
    "Bedroll",
    "Bedroll",
    "Blanket",
    "Book",
    "Glass Bottle",
    "Bucket",
    "Candle",
    "Map / Scroll Case",
    "Chain",
    "Chest",
    "Component Pouch",
    "Crowbar",
    "Druidic Focus",
    "Flask / Tankard",
    "Grappling Hook",
    "Hammer",
    "Hourglass",
    "Hunting Trap",
    "Bottle of Ink",
    "Ink Pen",
    "Ladder",
    "Lantern",
    "Lamp",
    "Lock and Key",
    "Magnifying Glass",
    "Mirror",
    "Flask of Oil",
    "Parchment",
    "Perfume Bottle",
    "Potions",
    "Vial of Poison",
    "Pouch",
    "Scrying Bones",
    "Rope",
    "Merchant's Scale",
    "Shovel",
    "Signet Ring",
    "Spellbook",
    "Tea Kettle",
    "Umbrella",
    "Needle and Thread"
]

const tools = [
    "Alchemist's Supplies",
    "Brewer's Supplies",
    "Calligrapher's Tools",
    "Cartographer's Tools",
    "Clockmaker's Kit",
    "Cobbler's Tools",
    "Cook's Utensils",
    "Glassblower's Tools",
    "Jeweler's Tools",
    "Leatherworker's Tools",
    "Mason's Tools",
    "Painter's Tools",
    "Smithing Tools",
    "Tinker's Tools",
    "Weaver's Tools",
    "Woodcarver's Tools",
    "Disguise Kit",
    "Forgery Kit",
    "Herbalism Kit",
    "Musical Instrument",
    "Navigator's Tools",
    "Poisoner's Kit",
    "Thieves' Tools",
    "Healer's Kit"
]

export { weapons, equipment, tools };


