const weapons = [
    "club",
    "dagger",
    "greatclub",
    "handaxe",
    "javelin",
    "light hammer",
    "mace",
    "quarterstaff",
    "sickle",
    "spear",
    "crossbow",
    "dart",
    "shortbow",
    "sling",
    "battleaxe",
    "flail",
    "glaive",
    "greataxe",
    "greatsword",
    "halberd",
    "lance",
    "longsword",
    "maul",
    "morningstar",
    "pike",
    "rapier",
    "scimitar",
    "shortsword",
    "trident",
    "war pick",
    "warhammer",
    "whip",
    "blowgun",
    "longbow",
    "net"
]

const equipment = [
    "an abacus",
    "a vial of acid",
    "a flask of Alchemist's Fire",
    "ammunition (arrows, blowgun needles, crossbow bolts, bullets, etc.)",
    "a vial of antitoxin",
    "some kind of arcane focus",
    "a backpack",
    "a bag of ball bearings",
    "a barrel",
    "a basket",
    "a bedroll",
    "a blanket",
    "a book",
    "a glass bottle",
    "a bucket",
    "a candle",
    "a scroll case",
    "a chain",
    "a chest",
    "a component pouch",
    "a crowbar",
    "some kind of druidic focus",
    "a tankard",
    "a flask",
    "a grappling hook",
    "a hammer",
    "an hourglass",
    "a hunting trap",
    "a bottle of ink",
    "an ink pen",
    "a wooden ladder",
    "a lantern",
    "a lamp",
    "a lock and key",
    "a magnifying glass",
    "a mirror",
    "a flask of oil",
    "some parchment",
    "a perfume bottle",
    "an assortment of potions",
    "a vial of poison",
    "a pouch",
    "scrying bones",
    "rope",
    "a merchant's scale",
    "a shovel",
    "a silver signet ring",
    "a spellbook",
    "a tea kettle",
    "an umbrella",
    "a needle and thread",
    "an ancient tome"
]

export { weapons, equipment };


