const plants = [
    "Seaweed",
    "Fern",
    "Desert Cacti",
    "Jade",
    "Flower",
    "Vines",
    "Poppies",
    "Grass / Dandelion",
    "Wild Flowers",
    "Carnivorous Plant",
    "Asparagas",
    "Pinecone",
    "Berries",
    "Ginger",
    "Tree Fruit",
    "Legume",
    "Gourd",
    "Artichoke",
    "Broccoli / Cauliflower",
    "Corn",
    "Grain",
    "Moss",
    "Lichen",
    "Mushroom",
    "Birch Tree",
    "Willow Tree",
    "Maple Tree",
    "Oak Tree",
    "Pine Tree",
    "Banyan"
]

const environments = [
    "Moon Cycles",
    "Starfield",
    "Crater / Asteroid",
    "Solar Flare",
    "Galaxy Form",
    "Volcano",
    "Planet Texture / Feature",
    "Cloud",
    "Cyclone",
    "Tornado"
]

const elements = [
    "Fire",
    "Electric Bolts",
    "Embers",
    "Molten Lava",
    "Icicles",
    "Fog",
    "Vapor",
    "Waves",
    "Dew Drops",
    "Ripples",
    "Frost / Snow",
    "Suds / Bubbles",
    "Tar / Gum",
    "Malachite",
    "Brick",
    "Mountain / Cliff Face",
    "Cobblestone",
    "Rust / Oxide",
    "Cracked Clay",
    "Stalactite / Stalagmite",
    "Glass / Crystal",
    "Powder / Sand",
    "Slate / Shale",
    "Cement / Sediment"
]

const personalities = [
    "Shy",
    "Bold",
    "Mischievous",
    "Angry",
    "Timid",
    "Aloof",
    "Cowardly",
    "Paranoid",
    "Deadpan",
    "Insane",
    "Jovial",
    "Hysterical",
    "Shifty",
    "Confused",
    "Carefree"
]

export { plants, environments, elements, personalities };