const plants = [
    "some seaweed",
    "a fern",
    "a desert cactus",
    "jade",
    "a flower",
    "vines",
    "poppies",
    "some grass",
    "a dandelion",
    "wild flowers",
    "a carnivorous plant",
    "asparagas",
    "a pinecone",
    "berries",
    "ginger",
    "a tree fruit",
    "a legume",
    "some type of gourd",
    "an artichoke",
    "broccoli",
    "cauliflower",
    "corn",
    "some grains",
    "moss",
    "lichen",
    "a mushroom",
    "a birch tree",
    "a willow tree",
    "a maple tree",
    "an oak tree",
    "a pine tree",
    "a banyan"
]

const environments = [
    "the moon cycles",
    "a starfield",
    "a crater",
    "an asteroid",
    "a solar flare",
    "some kind of galaxy form",
    "a active volcano",
    "a new planet",
    "a cloud",
    "a cyclone",
    "a tornado"
]

const elements = [
    "Fire",
    "Electric Bolts",
    "Embers",
    "Molten Lava",
    "Icicles",
    "Fog",
    "Vapor",
    "Waves",
    "Dew Drops",
    "Ripples",
    "Frost / Snow",
    "Suds / Bubbles",
    "Tar / Gum",
    "Malachite",
    "Brick",
    "Mountain / Cliff Face",
    "Cobblestone",
    "Rust / Oxide",
    "Cracked Clay",
    "Stalactite / Stalagmite",
    "Glass / Crystal",
    "Powder / Sand",
    "Slate / Shale",
    "Cement / Sediment"
]

const personalities = [
    "A shy",
    "A bold",
    "A mischievous",
    "An angry",
    "A timid",
    "An aloof",
    "A cowardly",
    "A paranoid",
    "A deadpan",
    "An insane",
    "A jovial",
    "A hysterical",
    "A shifty",
    "A confused",
    "A carefree"
]

export { plants, environments, elements, personalities };