const plants = [
    "Seaweed",
    "Fern",,
    "Desert Cacti",
    "Jade",
    "Flower",
    "Vines",
    "Poppies",
    "Grass / Dandelion",
    "Wild Flowers",
    "Carnivorous Plant",
    "Asparagas",
    "Pinecone",
    "Berries",
    "Ginger",
    "Tree Fruit",
    "Legume",
    "Gourd",
    "Artichoke",
    "Broccoli / Cauliflower",
    "Corn",
    "Grain",
    "Moss",
    "Lichen",
    "Mushroom",
    "Birch Tree",
    "Willow Tree",
    "Maple Tree",
    "Oak Tree",
    "Pine Tree",
    "Banyan"
]

const environments = [
    "Moon Cycles",
    "Starfield",
    "Crater / Asteroid",
    "Solar Flare",
    "Galaxy Form",
    "Volcano",
    "Planet Texture / Feature",
    "Cloud",
    "Cyclone",
    "Tornado"
]
export { plants, environments };